# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserToyExample < Formula
  desc ""
  homepage "https://github.com/cotramarko/homebrew-tools"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cotramarko/go-releaser-toy-example/releases/download/v0.0.9/go-releaser-toy-example_Darwin_x86_64.tar.gz"
      sha256 "d8936f5764f9fad85c4b183681d8d02376002612930706f1a9258b301fae0c44"

      def install
        bin.install "go-releaser-toy-example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cotramarko/go-releaser-toy-example/releases/download/v0.0.9/go-releaser-toy-example_Darwin_arm64.tar.gz"
      sha256 "ec21adc857ea3864cecbd943a3939fe2952514cd37c9f709357bc1144b161f8b"

      def install
        bin.install "go-releaser-toy-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cotramarko/go-releaser-toy-example/releases/download/v0.0.9/go-releaser-toy-example_Linux_x86_64.tar.gz"
      sha256 "2bc9edbb0c0e18fee1e4fdd467fc9ac626a7ea59a63051f958bed6d0855bb8d6"

      def install
        bin.install "go-releaser-toy-example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cotramarko/go-releaser-toy-example/releases/download/v0.0.9/go-releaser-toy-example_Linux_arm64.tar.gz"
      sha256 "39cbda447307a8620f4314f553c3e9e24cf656fe5aede95010bdc33c2a27ab91"

      def install
        bin.install "go-releaser-toy-example"
      end
    end
  end
end
