# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snapvault < Formula
  desc ""
  homepage "https://github.com/cotramarko/homebrew-tools"
  version "1.0.0-alpha"

  on_macos do
    on_intel do
      url "https://github.com/cotramarko/SnapVault/releases/download/v1.0.0-alpha/SnapVault_Darwin_x86_64.tar.gz"
      sha256 "8c2649136590db3d97f3e039cc0bd01966abf5f85d5aad9e52984bfb9bdf6fda"

      def install
        bin.install "SnapVault"
      end
    end
    on_arm do
      url "https://github.com/cotramarko/SnapVault/releases/download/v1.0.0-alpha/SnapVault_Darwin_arm64.tar.gz"
      sha256 "77f3fbf5411ab1fcb5ead996afe22b18485db559c623fdf4587f96e5867ea6e0"

      def install
        bin.install "SnapVault"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cotramarko/SnapVault/releases/download/v1.0.0-alpha/SnapVault_Linux_x86_64.tar.gz"
        sha256 "bf7a4381d4da318b20201bf883fcd6db026c35c9776d07355abe505a3d41b348"

        def install
          bin.install "SnapVault"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cotramarko/SnapVault/releases/download/v1.0.0-alpha/SnapVault_Linux_arm64.tar.gz"
        sha256 "c1ff3d4da59acad085e0b6d666b05580b5fffdb2358f3ba949e2ded09f3515a4"

        def install
          bin.install "SnapVault"
        end
      end
    end
  end
end
