# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snapvault < Formula
  desc ""
  homepage "https://github.com/cotramarko/homebrew-tools"
  version "1.0.0-alpha4"

  on_macos do
    on_intel do
      url "https://github.com/cotramarko/snapvault/releases/download/v1.0.0-alpha4/snapvault_Darwin_x86_64"
      sha256 "e19e3fe04bb89859353566b4b0d4cffebb9b4ce5eace0dfb15b0f8478579ccba"

      def install
        bin.install "snapvault_Darwin_x86_64" => "snapvault"
      end
    end
    on_arm do
      url "https://github.com/cotramarko/snapvault/releases/download/v1.0.0-alpha4/snapvault_Darwin_arm64"
      sha256 "59055399ebbc6cf972757263f36ea29024dcfdeaf76d3fe2a281ad6f712b0b64"

      def install
        bin.install "snapvault_Darwin_arm64" => "snapvault"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cotramarko/snapvault/releases/download/v1.0.0-alpha4/snapvault_Linux_x86_64"
        sha256 "973104bf518c5a19563e3d3b0e3ed65c57384c3903716c2ed4cc149d103bc088"

        def install
          bin.install "snapvault_Linux_x86_64" => "snapvault"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cotramarko/snapvault/releases/download/v1.0.0-alpha4/snapvault_Linux_arm64"
        sha256 "6122d62c6e521e6213ee65b6644828ede931a44414f62464c6e9379d90625a14"

        def install
          bin.install "snapvault_Linux_arm64" => "snapvault"
        end
      end
    end
  end
end
